---
- hosts:all
  vars_files:
    - config.yaml
  vars:
    default_motd: "Ansible Control node by {{ ansible_user }}"
    python_packages:
      - python3
      - python3-pip
  tasks:
    - name: Install Python 3 and Pip3
      package:
        name: "{{ python_packages }}"
        state: latest
      become: yes

    - name: Set pip3 as defult pip
      alternatives:
        name: pip
        path: /usr/bin/pip3
      become: yes

    - name: Set python3 as default python
      alternatives:
        name: python
        path: /usr/bin/python3
      become: yes

    - name: Install Java open-jdk
      package:
        name: java-1.8.0-openjdk
        state: latest
      become: yes

    - name: Create Motd
      copy:
        dest: /etc/motd
        content: "{{ motd_text | default(default_motd) }}"
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Create a user
      user:
        name: "{{ new_user }}"
        state: present
      become: yes
...
